# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

target 'DYZB' do
	pod 'Alamofire'
    pod 'Kingfisher'
  
  # Pods for DYZB

  target 'DYZBTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DYZBUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
